---
# This default profile is used when running a single instance completely standalone:
#spring.cloud.config.server.git.uri=ssh://localhost/config-repo
#  spring.cloud.config.server.git.clone-on-start=true
#  security.user.name=root
#  security.user.password=s3cr3t

spring:
  profiles: default
  cloud:
    config:
      server:
        git:
          uri: ssh://localhost/config-repo
          clone-on-start: true
  security:
    user:
      name: root
      password: 1111;


server:
  port: 8761
eureka:
  instance:
    hostname: my-eureka-server.com
  client:
    register-with-eureka: false
    fetch-registry: false


  # united-states, france, and vietnam illustrate running 3 intercommunicating instances.
  # This example has them running side-by-side on localhost
  # -- which is unrealistic in production
  # -- but does illustrate how multiple instances collaborate.
  #
  # Run by opening 3 separate command prompts:
  # java -jar -Dspring.profiles.active=united-states SpringCloudServiceRegistrationEurekaServer.jar
  # java -jar -Dspring.profiles.active=france SpringCloudServiceRegistrationEurekaServer.jar
  # java -jar -Dspring.profiles.active=vietnam SpringCloudServiceRegistrationEurekaServer.jar

#---
#spring:
#  profiles:
#    name: coordinate_computor
#  application:
#    name: city-rout-service
#server:
#  port: 8083
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8085/eureka
#  instance:
#    hostname: localhost

zuul:
  prefix: /api
  routes:
    rout-rest-service:
      path: /rest-service/**
      url: http://localhost:8090
    coordinate-computor:
      path: /coordinte/**
      url: http://localhost:8095



---
spring:
  profiles: united-states
  application:
    name: eureka-server-clustered   # ==> This is Service-Id
server:
#  port: 9001
port: 8085
eureka:
  instance:
    hostname: my-eureka-server-us.com
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://my-eureka-server-fr.com:9002/eureka/,http://my-eureka-server-vn.com:9003/eureka/

---
#spring:
#  profiles: france
#  application:
#    name: eureka-server-clustered   # ==> This is Service-Id
#server:
#  port: 9002
#eureka:
#  instance:
#    hostname: my-eureka-server-fr.com
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://my-eureka-server-us.com:9001/eureka/,http://my-eureka-server-vn.com:9003/eureka/
#
#---
#spring:
#  profiles: vietnam
#  application:
#    name: eureka-server-clustered    # ==> This is Service-Id
#server:
#  port: 9003
#eureka:
#  instance:
#    hostname: my-eureka-server-vn.com
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://my-eureka-server-us.com:9001/eureka/,http://my-eureka-server-fr.com:9002/eureka/
